@startuml 勤怠管理アクティビティ図

title 勤怠管理アクティビティ図

|社員|
:出勤;
start

:出勤ボタン押下;

|システム|
:出勤時間を登録;

stop

|社員|
:退勤;
start

:退勤ボタン押下;

|システム|

:実労働時間を算出;
if (実労働時間が足りない？) then
  :確認ダイアログ表示;

  |社員|
  if (退勤処理を中断？) then
    stop
  endif
endif

|システム|
:退勤時間を登録;

stop

@enduml
