@startuml 認証アクティビティ図

title 認証アクティビティ図

|ユーザ|
:ログイン;
start

:IDとパスワード入力;

|システム|
:IDとパスワードの検証;
if (バリデーション？) then
  :エラーメッセージ表示;
  stop
endif

if (認証失敗？) then
  :エラーメッセージ表示;
  stop
endif

:トークン発行;
stop

|ユーザ|
:ログアウト;
start

:ログアウトボタン押下;

|システム|
:トークンの無効化;

stop

@enduml
