@startuml 社員情報管理アクティビティ図

title 社員情報管理アクティビティ図

|人事担当|
:採用手続き;
start

:採用者の情報を入力;

|システム|
:採用者の情報を登録;
:人事トランザクションに追加;

stop

|人事担当|
:退職手続き;
start

:社員一覧ページより退職処理のボタンを押下;

|システム|
:退職者の情報を消去\n（退職フラグをtrueに）;
:人事トランザクションに追加;

stop

|人事担当|
:情報参照;
start

:社員一覧ページにアクセス;

|システム|
:社員一覧を出力;

stop

|人事担当|
:情報更新;
start

:更新する社員の情報を入力;

|システム|
:対象社員の情報を更新;

stop

@enduml
